version: '3.8'
services:
  db:
    image: postgres:15
    container_name: flowbiz_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flowbiz_dev
    ports:
      - "5432:5432"
    volumes:
      - flowbiz_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  flowbiz_data: